# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ecfa74da044be1dfe3f39ba1ae88d40334f522751e53fee44539d14f559e0143f016933ba93a53d52b133ef84c70afc59d185a72b3b2f12e1cf6d7cb188faec

test:
  secret_key_base: 95a411f9ef4935980e3a04abf43bf7b1db68303500e476d77c5ef68b7124dde8a7129d11d4c27df2627f93b5b573a9c9ff21103c3c8972b1572294b1f66bc024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
